version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5678:5678"  # For remote debugging if needed
    volumes:
      - .:/app
      - ./app:/app/app  # Explicit mount for hot reloading
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=hetu
      - MYSQL_PASSWORD=hetu123
      - MYSQL_DATABASE=hetudb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONDONTWRITEBYTECODE=1  # Prevents Python from writing .pyc files
      - PYTHONUNBUFFERED=1  # Prevents Python from buffering stdout and stderr
    depends_on:
      - db
      - redis
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/app", "--proxy-headers"]

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=hetudb
      - MYSQL_USER=hetu
      - MYSQL_PASSWORD=hetu123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql_dev_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "hetu", "--password=hetu123"]
      interval: 10s
      timeout: 5s
      retries: 50
      start_period: 30s

  redis:
    image: redis:7.0
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data

volumes:
  mysql_dev_data:  # Separate volume for development data
  redis_dev_data:  # Separate volume for development data
