version: '3.8'

services:
  app:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=hetu
      - MYSQL_PASSWORD=hetu123
      - MYSQL_DATABASE=hetudb
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=hetudb
      - MYSQL_USER=hetu
      - MYSQL_PASSWORD=hetu123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
